# Generated by Django 5.0.6 on 2024-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Branch Name"
                    ),
                ),
                ("city", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=150)),
                ("post_code", models.IntegerField()),
            ],
        ),
    ]
