# Generated by Django 5.0.6 on 2024-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "holding_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("village", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "post_office",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=150, null=True)),
                ("post_code", models.IntegerField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=150, null=True)),
                ("country", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Branch Name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
