# Generated by Django 5.0.6 on 2024-06-25 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchaddress",
            name="id",
        ),
        migrations.AlterField(
            model_name="branchaddress",
            name="branch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="branch.branch",
            ),
        ),
    ]
