# Generated by Django 5.0.6 on 2024-07-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0004_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="use_for",
            field=models.CharField(
                choices=[("H", "Human"), ("V", "Veterinary"), ("R", "R")], max_length=50
            ),
        ),
    ]
