# Generated by Django 5.0.6 on 2024-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0006_alter_medicine_generic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="brand",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="generic",
            field=models.CharField(max_length=150),
        ),
    ]
