# Generated by Django 5.0.6 on 2024-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0007_alter_medicine_brand_alter_medicine_generic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="soled",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
