# Generated by Django 5.0.6 on 2024-06-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="branch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branch.branch",
                verbose_name="",
            ),
        ),
    ]
