# Generated by Django 5.0.6 on 2024-06-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user_details",
            ),
        ),
    ]
